import type { Metadata } from "next";
import "./ui/globals.css";
import { Header } from "@/app/ui/header";
import { Footer } from "@/app/ui/footer";
import { raleway } from "@/app/ui/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.className} antialiased bg-dark-700 text-white flex flex-col min-h-screen`}
      >
        <Header />
        <main className="pt-20 md:pt-[100px]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
